# Site settings
title: IF-ELSE-THEN  
email: axap288@gmail.com 
description: > # th means to ignore newlines until "baseurl:"
    liunian is blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: liunian_2002 
github_username: axap288 

# Build settings
markdown: kramdown
